name: CI/CD Parcial 3

on:
  push:
    branches:
      - main
      - master
      - parcial3-pruebas-docker-Vilmar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c�digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Desplegar en la m�quina virtual
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/Aplicaciones-y-Servicios-Web-Equipo-6-2026
            git pull origin parcial3-pruebas-docker-Vilmar
            docker stop contenedor-api || true
            docker rm contenedor-api || true
            docker build -t api-parcial3 .
            docker run -d -p 8000:8000 --env-file .env --name contenedor-api api-parcial3
